# Generated by Django 4.0 on 2022-06-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='photos',
            field=models.CharField(max_length=100, verbose_name='Урл фотографии'),
        ),
    ]
