# Generated by Django 4.0 on 2022-06-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_remove_pictures_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category'),
        ),
    ]
