# Generated by Django 4.0 on 2022-06-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pictures_not_upload_pictures_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='not_upload',
            field=models.BooleanField(blank=True, default=False, verbose_name='Не загружать из ВК'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='visible',
            field=models.BooleanField(blank=True, default=False, verbose_name='Отображать на главной'),
        ),
    ]
