# Generated by Django 4.0 on 2022-06-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_pictures_category_alter_pictures_not_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='not_upload',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Не загружать из ВК'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='visible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отображать на главной'),
        ),
    ]
